-- https://app.snowflake.com/dvohytg/tcb69711/#/homepage


USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE DATABASE STREAMLIT_DB;
CREATE OR REPLACE SCHEMA WORKSHOP;

SELECT * 
FROM STREAMLIT_DB.WORKSHOP.SURVEY_RESPONSES;

TRUNCATE TABLE STREAMLIT_DB.WORKSHOP.SURVEY_RESPONSES;
