-- https://app.snowflake.com/dvohytg/tcb69711/#/homepage
-- https://app.snowflake.com/dvohytg/tcb69711/w5BM9Tum2Lpx#query


USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE DATABASE STREAMLIT_DB;
CREATE OR REPLACE SCHEMA WORKSHOP;

SELECT * 
FROM STREAMLIT_DB.WORKSHOP.SURVEY_RESPONSES;

DROP TABLE IF EXISTS STREAMLIT_DB.WORKSHOP.SURVEY_RESPONSES;
TRUNCATE TABLE STREAMLIT_DB.WORKSHOP.SURVEY_RESPONSES;
